// Generated by https://quicktype.io

export interface TaskResponse {
    id:          string;
    title:       string;
    description: string;
    done:        boolean;
    createdAt:   string;
    updatedAt:   string;
    userId:      number | null;
    User: {
        id: number;
        username: string;
        email: string;
        createdAt: string;
        updatedAt: string;
    }
};

export interface TaskData {
    title: string;
    description: string;
    done: boolean;
    updatedAt?:  boolean | string;
};

export interface TaskDataResponse {
    data: TaskResponse;
};